# Generated by Django 3.2.9 on 2021-11-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=50)),
                ('Valor', models.IntegerField()),
                ('Descricao', models.CharField(max_length=500)),
                ('DataHoraEnvio', models.DateTimeField()),
            ],
        ),
    ]
